package io.dagger.annotation.processor;

import io.dagger.module.info.EnumInfo;
import io.dagger.module.info.FieldInfo;
import io.dagger.module.info.FunctionInfo;
import io.dagger.module.info.ModuleInfo;
import io.dagger.module.info.ObjectInfo;
import io.dagger.module.info.ParameterInfo;
import java.util.ArrayList;
import java.util.List;

/**
 * The manifest-v2 backend: the same {@link ModuleInfo} the JavaPoet backend turns into a runtime
 * {@code register()} call, rendered instead as a Dang {@code ModuleEntrypoint}.
 *
 * <p>The two backends must describe the same schema. Read {@code types()} here against
 * {@code register()} in {@link DaggerModuleAnnotationProcessor} when changing either.
 */
final class DangEntrypointRenderer {

  private static final String MAVEN_IMAGE =
      "maven:3.9.9-eclipse-temurin-21-alpine@sha256:4cbb8bf76c46b97e028998f2486ed014759a8e932480431039bdb93dffe6813e";
  private static final String JRE_IMAGE = "eclipse-temurin:21-jre-alpine";

  private static final String PICK_JAR =
      "set -e; jar=$(ls -1 target/*.jar 2>/dev/null | grep -v '/original-' | head -n1);"
          + " test -n \"$jar\" || { echo \"no packaged jar found in $(pwd)/target\" >&2; exit 1; };"
          + " cp \"$jar\" /tmp/module.jar";

  private DangEntrypointRenderer() {}

  static String render(ModuleInfo moduleInfo) {
    // DaggerType.of classifies a named type as an enum only when this static says so.
    DaggerType.setKnownEnums(moduleInfo.enumInfos().keySet());

    List<String> defs = new ArrayList<>();
    for (ObjectInfo object : moduleInfo.objects()) {
      defs.add(renderObject(object));
    }
    for (EnumInfo enumInfo : moduleInfo.enumInfos().values()) {
      defs.add(renderEnum(enumInfo));
    }

    StringBuilder b = new StringBuilder();
    b.append("# This file has been generated by dagger-java-sdk. DO NOT EDIT.\n\n");
    b.append("type Entrypoint implements ModuleEntrypoint {\n");
    b.append(jarField());
    b.append("\n  pub types(workspace: Workspace!): [TypeDef!]! {\n");
    b.append("    [\n");
    for (int i = 0; i < defs.size(); i++) {
      b.append(Dang.indent(defs.get(i), 6));
      b.append(i == defs.size() - 1 ? "\n" : ",\n");
    }
    b.append("    ]\n");
    b.append("  }\n\n");
    b.append(callField());
    b.append("}\n");
    return b.toString();
  }

  private static String jarField() {
    return String.join(
        "\n",
        "  let jar(workspace: Workspace!): File! {",
        "    container",
        "      .from(" + Dang.quote(MAVEN_IMAGE) + ")",
        "      .withoutEntrypoint",
        "      .withMountedCache(",
        "        path: \"/root/.m2\",",
        "        cache: cacheVolume(\"sdk-java-maven-m2\"),",
        "        sharing: CacheSharingMode.LOCKED,",
        "      )",
        "      .withDirectory(\"/src\", workspace.directory(\"/\"), exclude: [\"**/target/**\"])",
        "      .withWorkdir(\"/src/\" + workspace.cwd)",
        "      .withExec([\"mvn\", \"package\", \"-DskipTests\", \"--threads\", \"1C\", \"--no-transfer-progress\"])",
        "      # The shade plugin leaves the pre-shaded artifact beside the shaded one.",
        "      .withExec([\"sh\", \"-c\", " + Dang.quote(PICK_JAR) + "])",
        "      .file(\"/tmp/module.jar\")",
        "  }",
        "");
  }

  private static String callField() {
    return String.join(
        "\n",
        "  pub call(",
        "    workspace: Workspace!,",
        "    receiverType: String!,",
        "    receiverValue: JSON,",
        "    fnName: String!,",
        "    fnArgs: JSON!,",
        "  ): JSON! {",
        "    let request = JSON.encode({{",
        "      receiverType: receiverType,",
        "      receiverValue: receiverValue,",
        "      fnName: fnName,",
        "      fnArgs: fnArgs,",
        "    }})",
        "    let result = container",
        "      .from(" + Dang.quote(JRE_IMAGE) + ")",
        "      .withoutEntrypoint",
        "      .withFile(\"/opt/module/module.jar\", jar(workspace))",
        "      .withWorkdir(\"/opt/module\")",
        "      .withExec(",
        "        [\"java\", \"-jar\", \"/opt/module/module.jar\", \"engine-call\"],",
        "        stdin: request,",
        "        experimentalPrivilegedNesting: true,",
        "      )",
        "      .stdout",
        "    (result :: JSON!)",
        "  }",
        "");
  }

  private static String renderObject(ObjectInfo object) {
    StringBuilder b = new StringBuilder("typeDef.withObject(").append(Dang.quote(object.name()));
    appendDescription(b, object.description());
    b.append(")");

    for (FunctionInfo function : object.functions()) {
      b.append("\n  .withFunction(\n")
          .append(Dang.indent(renderFunction(object, function), 4))
          .append("\n  )");
    }
    for (FieldInfo field : object.fields()) {
      b.append("\n  .withField(")
          .append(Dang.quote(field.name()))
          .append(", ")
          .append(DaggerType.of(field.type()).toDangTypeDef());
      appendDescription(b, field.description());
      b.append(")");
    }
    if (object.constructor().isPresent()) {
      b.append("\n  .withConstructor(\n")
          .append(Dang.indent(renderFunction(object, object.constructor().get()), 4))
          .append("\n  )");
    }
    return b.toString();
  }

  private static String renderEnum(EnumInfo enumInfo) {
    StringBuilder b = new StringBuilder("typeDef.withEnum(").append(Dang.quote(enumInfo.name()));
    appendDescription(b, enumInfo.description());
    b.append(")");
    for (var value : enumInfo.values()) {
      b.append("\n  .withEnumValue(").append(Dang.quote(value.value()));
      appendDescription(b, value.description());
      b.append(")");
    }
    return b.toString();
  }

  private static String renderFunction(ObjectInfo object, FunctionInfo function) {
    boolean isConstructor = "<init>".equals(function.name());
    String returnType =
        isConstructor
            ? DaggerType.of(object.qualifiedName()).toDangTypeDef()
            : DaggerType.of(function.returnType()).toDangTypeDef();

    StringBuilder b =
        new StringBuilder("function(")
            .append(Dang.quote(isConstructor ? "" : function.name()))
            .append(", ")
            .append(returnType)
            .append(")");

    if (isNotBlank(function.description())) {
      b.append("\n  .withDescription(").append(Dang.quote(function.description())).append(")");
    }
    if (function.isCheck()) {
      b.append("\n  .withCheck");
    }
    if (function.isGenerate()) {
      b.append("\n  .withGenerator");
    }
    if (function.isUp()) {
      b.append("\n  .withUp");
    }
    for (ParameterInfo parameter : function.parameters()) {
      b.append("\n  .withArg(").append(Dang.quote(parameter.name())).append(", ");
      b.append(DaggerType.of(parameter.type()).toDangTypeDef());
      // Argument optionality is recorded on ParameterInfo, not on the type: the processor strips
      // Optional<...> before DaggerType ever sees it.
      if (parameter.optional()) {
        b.append(".withOptional(true)");
      }
      if (isNotBlank(parameter.description())) {
        b.append(", description: ").append(Dang.quote(parameter.description()));
      }
      if (parameter.defaultValue().isPresent()) {
        b.append(", defaultValue: JSON.decode(")
            .append(Dang.quote(parameter.defaultValue().get()))
            .append(")");
      }
      if (parameter.defaultPath().isPresent()) {
        b.append(", defaultPath: ").append(Dang.quote(parameter.defaultPath().get()));
      }
      if (parameter.ignore().isPresent()) {
        b.append(", ignore: [");
        String[] ignore = parameter.ignore().get();
        for (int i = 0; i < ignore.length; i++) {
          b.append(i == 0 ? "" : ", ").append(Dang.quote(ignore[i]));
        }
        b.append("]");
      }
      b.append(")");
    }
    return b.toString();
  }

  private static void appendDescription(StringBuilder b, String description) {
    if (isNotBlank(description)) {
      b.append(", description: ").append(Dang.quote(description));
    }
  }

  private static boolean isNotBlank(String value) {
    return value != null && !value.isBlank();
  }
}
